### ISSUE TITLE
Kraken = Cracking Error

### ISSUE THREAD

**Issue by masahidehoshi1** [executium/trending-historical-cryptocurrency-news#1]
There is an issue with Kraken somehow showing to be Cracking on the Spread Chart.

**Comment by executium** [comment]
Will be the google translate.

Scrolling through many of them will present this. 

Just the way it renders. 

Will be a case of not being on the English translate. Kraken is taken as a typo of cracking in many spellchecker, so the translate system by Google would auto spell check, then come up with that
